"use client";

import { useState } from "react";
import { Bell, Bookmark, Bot, Download, Mic, Plus, RefreshCw, Save, Search, Trash2 } from "lucide-react";
import { economicEvents, heatmap, news, portfolio as starterPortfolio, watchlist } from "@/lib/mock-data";
import type { NewsArticle, PortfolioHolding } from "@/lib/types";
import { useMarketStore } from "@/store/market-store";
import { Metric, Panel, StatusPill } from "./ui";

const categories = ["All", "AI", "Space", "Semiconductor", "Energy", "Crypto", "Thai Stocks", "US Stocks"];

export function NewsPage() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const [items, setItems] = useState<NewsArticle[]>(news);
  const [bookmarks, setBookmarks] = useState<string[]>(news.filter((item) => item.saved).map((item) => item.id));
  async function refreshNews() {
    const response = await fetch(`/api/news?q=${encodeURIComponent(query)}&category=${category === "All" ? "" : encodeURIComponent(category)}`, { cache: "no-store" });
    const data = (await response.json()) as { items: NewsArticle[] };
    setItems(data.items?.length ? data.items : news);
  }
  const filtered = items.filter((article) => (category === "All" || article.category === category) && `${article.ticker} ${article.title} ${article.summaryTh}`.toLowerCase().includes(query.toLowerCase()));
  return <Panel className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.2em] text-cyan-300">Realtime News Feed</p><h2 className="mt-1 text-xl font-semibold text-white">News AI พร้อมวันที่, sentiment, impact score</h2></div><button onClick={refreshNews} className="flex items-center gap-2 rounded-md bg-cyan-300 px-3 py-2 text-sm font-medium text-slate-950"><RefreshCw size={15} />Refresh</button></div><div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto]"><div className="flex items-center gap-2 rounded-md border border-white/10 bg-white/[0.04] px-3"><Search size={16} className="text-slate-500" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-10 w-full bg-transparent text-sm text-slate-100 outline-none" placeholder="Search ticker, source, headline..." /></div><select value={category} onChange={(e) => setCategory(e.target.value)} className="h-10 rounded-md border border-white/10 bg-slate-950 px-3 text-sm text-slate-100 outline-none">{categories.map((item) => <option key={item}>{item}</option>)}</select></div><div className="mt-4 space-y-3">{filtered.map((article) => <article key={article.id} className="rounded-md border border-white/10 bg-white/[0.035] p-4"><div className="flex flex-wrap items-center gap-2"><StatusPill tone={article.sentiment === "Bullish" ? "up" : article.sentiment === "Bearish" ? "down" : "neutral"}>{article.sentiment}</StatusPill><StatusPill tone="info">{article.category}</StatusPill><span className="font-mono text-xs text-slate-500">{article.ticker} · {article.source} · {article.date} {article.time}</span><button onClick={() => setBookmarks((current) => current.includes(article.id) ? current.filter((id) => id !== article.id) : [...current, article.id])} title="Bookmark" className="ml-auto text-slate-400 hover:text-cyan-200"><Bookmark size={16} fill={bookmarks.includes(article.id) ? "currentColor" : "none"} /></button></div><h3 className="mt-3 text-base font-semibold text-white">{article.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{article.summaryTh}</p><div className="mt-3 flex items-center gap-3"><div className="h-1.5 flex-1 rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-cyan-300 to-purple-400" style={{ width: `${article.impact}%` }} /></div><span className="font-mono text-xs text-slate-400">Impact {article.impact}</span></div></article>)}</div></Panel>;
}

export function PortfolioPage() {
  const quotes = useMarketStore((state) => state.quotes);
  const [holdings, setHoldings] = useState<PortfolioHolding[]>(starterPortfolio);
  const [form, setForm] = useState({ ticker: "NVDA", quantity: 1, buyPrice: 100, targetPrice: 150, stopLoss: 90 });
  const rows = holdings.map((holding) => { const live = quotes.find((quote) => quote.ticker === holding.ticker); const currentPrice = live?.price ?? holding.currentPrice; const value = holding.quantity * currentPrice; const cost = holding.quantity * holding.buyPrice; return { ...holding, currentPrice, value, cost, pnl: value - cost, roi: ((value - cost) / cost) * 100 }; });
  const total = rows.reduce((sum, row) => sum + row.value, 0);
  return <div className="grid gap-4 xl:grid-cols-[1fr_360px]"><Panel className="p-4"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold text-white">Portfolio Tracker ใช้งานได้</h2><button className="flex items-center gap-2 rounded-md border border-white/10 px-3 py-2 text-sm text-slate-300"><Download size={15} />Export CSV</button></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><Metric label="Total Value" value={`$${total.toLocaleString("en-US", { maximumFractionDigits: 0 })}`} delta="live marks" tone="up" /><Metric label="Positions" value={`${rows.length}`} delta="editable" tone="neutral" /><Metric label="Best ROI" value={`${Math.max(...rows.map((row) => row.roi)).toFixed(1)}%`} delta="top" tone="up" /></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="text-left text-xs uppercase tracking-[0.16em] text-slate-500"><tr><th className="py-2">Ticker</th><th>Qty</th><th>Avg Cost</th><th>Live Price</th><th>P/L</th><th>ROI</th><th>Target</th><th>Stop</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.ticker} className="border-t border-white/10"><td className="py-3 font-mono text-white">{row.ticker}</td><td>{row.quantity}</td><td>${row.buyPrice.toFixed(2)}</td><td>${row.currentPrice.toFixed(2)}</td><td className={row.pnl >= 0 ? "text-emerald-300" : "text-rose-300"}>${row.pnl.toFixed(0)}</td><td>{row.roi.toFixed(1)}%</td><td>${row.targetPrice}</td><td>${row.stopLoss}</td><td><button onClick={() => setHoldings((current) => current.filter((item) => item.ticker !== row.ticker))} className="text-slate-500 hover:text-rose-300"><Trash2 size={15} /></button></td></tr>)}</tbody></table></div></Panel><Panel className="p-4"><h3 className="font-semibold text-white">Add / Update Position</h3><div className="mt-4 space-y-3"><select value={form.ticker} onChange={(e) => setForm({ ...form, ticker: e.target.value })} className="h-10 w-full rounded-md border border-white/10 bg-slate-950 px-3 text-slate-100">{watchlist.map((quote) => <option key={quote.ticker}>{quote.ticker}</option>)}</select>{(["quantity", "buyPrice", "targetPrice", "stopLoss"] as const).map((key) => <input key={key} type="number" value={form[key]} onChange={(e) => setForm({ ...form, [key]: Number(e.target.value) })} className="h-10 w-full rounded-md border border-white/10 bg-white/[0.03] px-3 text-slate-100 outline-none" placeholder={key} />)}<button onClick={() => { const quote = quotes.find((item) => item.ticker === form.ticker) ?? watchlist[0]; setHoldings((current) => [...current.filter((item) => item.ticker !== form.ticker), { ...form, currentPrice: quote.price, sector: quote.sector, currency: form.ticker.endsWith(".BK") ? "THB" : "USD" }]); }} className="flex w-full items-center justify-center gap-2 rounded-md bg-cyan-300 px-3 py-2 font-medium text-slate-950"><Plus size={16} />Save Position</button></div></Panel></div>;
}

export function ScreenerPage() { const quotes = useMarketStore((state) => state.quotes); const [sector, setSector] = useState("All"); const [minRsi, setMinRsi] = useState(0); const [onlyBreakout, setOnlyBreakout] = useState(false); const sectors = ["All", ...Array.from(new Set(quotes.map((quote) => quote.sector)))]; const rows = quotes.filter((quote) => (sector === "All" || quote.sector === sector) && quote.rsi >= minRsi && (!onlyBreakout || quote.rsi > 65 || quote.changePercent > 2)); return <Panel className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold text-white">Stock Screener ใช้งานได้</h2><StatusPill tone="info">{rows.length} matches</StatusPill></div><div className="mt-4 grid gap-3 md:grid-cols-3"><select value={sector} onChange={(e) => setSector(e.target.value)} className="h-10 rounded-md border border-white/10 bg-slate-950 px-3 text-slate-100">{sectors.map((item) => <option key={item}>{item}</option>)}</select><label className="rounded-md border border-white/10 bg-white/[0.03] px-3 py-2 text-sm text-slate-300">Min RSI {minRsi}<input type="range" min="0" max="80" value={minRsi} onChange={(e) => setMinRsi(Number(e.target.value))} className="ml-3 align-middle" /></label><button onClick={() => setOnlyBreakout((value) => !value)} className={`rounded-md border px-3 py-2 text-sm ${onlyBreakout ? "border-cyan-300/40 bg-cyan-300/15 text-cyan-100" : "border-white/10 text-slate-300"}`}>Breakout only</button></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{rows.map((quote) => <Metric key={quote.ticker} label={`${quote.ticker} · ${quote.sector}`} value={`$${quote.price.toFixed(2)}`} delta={`${quote.changePercent > 0 ? "+" : ""}${quote.changePercent}% · RSI ${quote.rsi}`} tone={quote.changePercent >= 0 ? "up" : "down"} />)}</div></Panel>; }

export function HeatmapPage() { const [filter, setFilter] = useState("All"); const sectors = ["All", ...Array.from(new Set(heatmap.map((item) => item.sector)))]; const rows = heatmap.filter((item) => filter === "All" || item.sector === filter); return <Panel className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold text-white">Interactive Market Heatmap</h2><select value={filter} onChange={(e) => setFilter(e.target.value)} className="h-10 rounded-md border border-white/10 bg-slate-950 px-3 text-slate-100">{sectors.map((item) => <option key={item}>{item}</option>)}</select></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{rows.map((stock) => <button key={stock.ticker} className={`rounded-md p-4 text-left transition hover:scale-[1.02] ${stock.change >= 0 ? "bg-emerald-400/15" : "bg-rose-400/15"}`} style={{ minHeight: 80 + stock.size }}><div className="font-mono text-lg text-white">{stock.ticker}</div><div className={stock.change >= 0 ? "text-emerald-300" : "text-rose-300"}>{stock.change >= 0 ? "+" : ""}{stock.change}%</div><div className="mt-2 text-xs text-slate-500">{stock.sector}</div></button>)}</div></Panel>; }

export function CalendarPage() { const [impact, setImpact] = useState("All"); const rows = economicEvents.filter((event) => impact === "All" || event.impact === impact); return <Panel className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold text-white">Economic Calendar</h2><select value={impact} onChange={(e) => setImpact(e.target.value)} className="h-10 rounded-md border border-white/10 bg-slate-950 px-3 text-slate-100">{["All", "High", "Medium"].map((item) => <option key={item}>{item}</option>)}</select></div><div className="mt-4 grid gap-3 md:grid-cols-2">{rows.map((event) => <div key={event.event} className="rounded-md border border-white/10 bg-white/[0.035] p-4"><div className="flex items-center justify-between"><h3 className="font-semibold text-white">{event.event}</h3><StatusPill tone={event.impact === "High" ? "down" : "neutral"}>{event.impact}</StatusPill></div><p className="mt-2 text-sm text-slate-400">{event.date} · Forecast {event.forecast}</p><button className="mt-3 flex items-center gap-2 text-sm text-cyan-200"><Bell size={15} />Set alert</button></div>)}</div></Panel>; }

export function WhalesPage() { const rows = [{ name: "Institutional Flow", ticker: "NVDA", value: "+$420M", signal: "Accumulation" }, { name: "CEO Transaction", ticker: "RKLB", value: "No sale", signal: "Stable" }, { name: "Congress Trade", ticker: "MSFT", value: "+$1.2M", signal: "Watch" }, { name: "Hedge Fund 13F", ticker: "AMD", value: "+8.4%", signal: "Buying" }]; return <Panel className="p-4"><h2 className="text-xl font-semibold text-white">Insider / Whale Tracking</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{rows.map((row) => <div key={row.name} className="rounded-md border border-white/10 bg-white/[0.035] p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">{row.name}</p><div className="mt-3 flex items-center justify-between"><span className="font-mono text-xl text-white">{row.ticker}</span><StatusPill tone={row.signal === "Buying" || row.signal === "Accumulation" ? "up" : "neutral"}>{row.signal}</StatusPill></div><p className="mt-2 font-mono text-slate-300">{row.value}</p></div>)}</div></Panel>; }

export function MultiChartPage() { const { quotes, setSelectedTicker } = useMarketStore(); const [grid, setGrid] = useState(4); const rows = quotes.slice(0, grid); return <Panel className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold text-white">Multi Chart Screen</h2><div className="flex gap-2">{[2, 4, 6, 8].map((item) => <button key={item} onClick={() => setGrid(item)} className={`rounded-md px-3 py-2 text-sm ${grid === item ? "bg-cyan-300 text-slate-950" : "border border-white/10 text-slate-300"}`}>{item} Grid</button>)}</div></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{rows.map((quote, index) => <button key={quote.ticker} onClick={() => setSelectedTicker(quote.ticker)} className="rounded-md border border-white/10 bg-black/20 p-3 text-left"><div className="flex items-center justify-between"><span className="font-mono text-white">{quote.ticker}</span><span className={quote.changePercent >= 0 ? "text-emerald-300" : "text-rose-300"}>{quote.changePercent}%</span></div><div className="mt-3 flex h-28 items-end gap-1">{Array.from({ length: 42 }, (_, i) => <span key={i} className="flex-1 rounded-t bg-cyan-300/40" style={{ height: `${(20 + Math.abs(Math.sin(i / 3 + index)) * 75).toFixed(1)}%` }} />)}</div></button>)}</div></Panel>; }

export function CopilotPageFull() { const [prompt, setPrompt] = useState("วิเคราะห์ NVDA พร้อมแนวรับแนวต้าน"); const [mode, setMode] = useState<"beginner" | "advanced">("advanced"); const [answer, setAnswer] = useState("พร้อมตอบคำถามหุ้นเป็นภาษาไทย กด Ask Copilot เพื่อเริ่มวิเคราะห์"); const [loading, setLoading] = useState(false); async function ask() { setLoading(true); try { const response = await fetch("/api/copilot", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prompt, mode }) }); const data = (await response.json()) as { answer: string; disclaimer: string }; setAnswer(`${data.answer}\n\n${data.disclaimer}`); } finally { setLoading(false); } } return <div className="grid gap-4 xl:grid-cols-[1fr_360px]"><Panel className="p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold text-white">AI Stock Copilot ใช้งานได้</h2><StatusPill tone="info">{mode}</StatusPill></div><div className="mt-4 flex gap-2">{(["beginner", "advanced"] as const).map((item) => <button key={item} onClick={() => setMode(item)} className={`rounded-md px-3 py-2 text-sm ${mode === item ? "bg-purple-300 text-slate-950" : "border border-white/10 text-slate-300"}`}>{item}</button>)}</div><textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} className="mt-4 min-h-32 w-full resize-none rounded-md border border-white/10 bg-white/[0.03] p-3 text-slate-100 outline-none" /><button onClick={ask} disabled={loading} className="mt-3 flex items-center gap-2 rounded-md bg-cyan-300 px-4 py-2 font-medium text-slate-950"><Bot size={16} />{loading ? "Analyzing..." : "Ask Copilot"}</button><pre className="mt-4 whitespace-pre-wrap rounded-md border border-white/10 bg-black/30 p-4 text-sm leading-6 text-slate-300">{answer}</pre></Panel><Panel className="p-4"><h3 className="font-semibold text-white">Quick Prompts</h3><div className="mt-4 space-y-2">{["หุ้นไหนกำลัง breakout", "สรุปข่าว AI วันนี้", "พอร์ตเสี่ยงไหม", "เปรียบเทียบ TSLA กับ RKLB"].map((item) => <button key={item} onClick={() => setPrompt(item)} className="w-full rounded-md border border-white/10 px-3 py-2 text-left text-sm text-slate-300">{item}</button>)}</div></Panel></div>; }

export function SettingsPageFull() { const [theme, setTheme] = useState("Cyan"); const [currency, setCurrency] = useState("USD"); const [language, setLanguage] = useState("TH"); const [alerts, setAlerts] = useState(true); return <Panel className="p-4"><h2 className="text-xl font-semibold text-white">Settings ใช้งานได้</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["Theme", theme, setTheme, ["Cyan", "Blue", "Purple"]], ["Currency", currency, setCurrency, ["USD", "THB"]], ["Language", language, setLanguage, ["TH", "EN"]]].map(([label, value, setter, options]) => <div key={label as string} className="rounded-md border border-white/10 bg-white/[0.035] p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">{label as string}</p><div className="mt-3 flex gap-2">{(options as string[]).map((option) => <button key={option} onClick={() => (setter as (v: string) => void)(option)} className={`rounded-md px-3 py-2 text-sm ${value === option ? "bg-cyan-300 text-slate-950" : "border border-white/10 text-slate-300"}`}>{option}</button>)}</div></div>)}<div className="rounded-md border border-white/10 bg-white/[0.035] p-4"><p className="text-xs uppercase tracking-[0.16em] text-slate-500">Notifications</p><button onClick={() => setAlerts((value) => !value)} className={`mt-3 rounded-md px-3 py-2 text-sm ${alerts ? "bg-emerald-300 text-slate-950" : "border border-white/10 text-slate-300"}`}>{alerts ? "Enabled" : "Disabled"}</button></div></div><button className="mt-4 flex items-center gap-2 rounded-md bg-cyan-300 px-4 py-2 font-medium text-slate-950"><Save size={16} />Save Settings</button></Panel>; }
